const RENDER_HOME = "RENDER_HOME";
const RENDER_ABOUT = "RENDER_ABOUT";
const RENDER_SERVICES = "RENDER_SERVICES";
const RENDER_DOCTORS = "RENDER_DOCTORS";

export default {
    RENDER_HOME,
    RENDER_ABOUT,
    RENDER_SERVICES,
    RENDER_DOCTORS
}